LOG_FILE: auto
LOG_LVL: SUCCESS
LOG_RETENTION: 5d

SERVICES_NAMES: [
  app-service1,
  app-service2,
  app-service3,
  app-service4,
  app-service5
]
PATCH_FILE_TEMPLATE: "k8s_deployments/nodeport-service-patch-template.yaml"