# logs
LOG_FILE: auto
LOG_LVL: INFO
LOG_RETENTION: 5d

# k8s
MASTER_NODE_IP: "10.2.255.1"
SERVICES_NAMES: [
  app-service1,
  app-service2,
  app-service3,
  app-service4,
  app-service5
]
PATCH_FILE_TEMPLATE: "k8s_deployments/nodeport-service-patch-template.yaml"

# state repository
STATE_PATH: "./state.json"
STATE_REPOSITORY_URL: "http://localhost:5000/state"
STATE_UPDATE_INTERVAL: 50

# app reconfigurator
APP_RECONFIGURATOR_URL: "http://localhost:5100/update"

# user
USER_INTERVAL: 2

# adversary
EXPLOIT_TIME: 5
LOWEST_NODE_PORT: 30000
HIGHEST_NODE_PORT: 32767
P1: 0.5
P2: 0.0

#cpu mem measurement
EXPORT_PATH: "cpu_mem.csv"
