apiVersion: apps/v1
kind: Deployment
metadata:
  name: false-app
spec:
  selector:
    matchLabels:
      app: false-app
  replicas: 2
  template:
    metadata:
      labels:
        app: false-app
    spec:
      containers:
      - name: false-app
        image: cyberorzech/repo:false-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred